### ISSUE TITLE
Css and images

### ISSUE THREAD

**Issue by OskarKlintrot** [beanloop/tscomp#1]
I try to learn how tscomp is working by creating [an example](https://github.com/OskarKlintrot/tscomp-examples/tree/develop). However, when I try to include a css-file in `index.html` with `<link rel="stylesheet" href="./assets/css/main.css" />` then I get some build error from Html Webpack Plugin:

```
Html Webpack Plugin:
  ReferenceError: window is not defined
  
  - addStyles.js?:14 eval
    C:\_dev\tscomp-example\tscomp-example-client/~/style-loader/addStyles.js?:14:30
  
  - addStyles.js?:9 eval
    C:\_dev\tscomp-example\tscomp-example-client/~/style-loader/addStyles.js?:9:47
  
  - addStyles.js?:31 module.exports
    C:\_dev\tscomp-example\tscomp-example-client/~/style-loader/addStyles.js?:31:68
  
  - main.css?:7 eval
    C:\_dev\tscomp-example\tscomp-example-client/src/assets/css/main.css?:7:82
  
  - index.html:561 Object.
    C:/_dev/tscomp-example/tscomp-example-client/src/index.html:561:2
  
  - index.html:519 __webpack_require__
    C:/_dev/tscomp-example/tscomp-example-client/src/index.html:519:30
  
  - index.html:50 fn
    C:/_dev/tscomp-example/tscomp-example-client/src/index.html:50:20
  
  - loader.js:1 eval
    C:\_dev\tscomp-example\tscomp-example-client/src/index.html?./~/html-webpack-plugin/lib/loader.js:1:    104
  
  - index.html:552 Object.
    C:/_dev/tscomp-example/tscomp-example-client/src/index.html:552:2
  
  - index.html:519 __webpack_require__
    C:/_dev/tscomp-example/tscomp-example-client/src/index.html:519:30
  
  - From previous event:
  
  - index.js:108 Compiler.
    [tscomp-example-client]/[html-webpack-plugin]/index.js:108:8
  
  - Tapable.js:71 Compiler.applyPluginsAsync
    [tscomp-example-client]/[tapable]/lib/Tapable.js:71:13
  
  - Compiler.js:226 Compiler.emitAssets
    [tscomp-example-client]/[webpack]/lib/Compiler.js:226:7
  
  - Compiler.js:54 Watching.
    [tscomp-example-client]/[webpack]/lib/Compiler.js:54:18
  
  - Compiler.js:403 
    [tscomp-example-client]/[webpack]/lib/Compiler.js:403:12
  
  - Tapable.js:67 Compiler.next
    [tscomp-example-client]/[tapable]/lib/Tapable.js:67:11
  
  - index.js:362 Compiler.
    [tscomp-example-client]/[ts-loader]/index.js:362:9
  
  - Tapable.js:69 Compiler.next
    [tscomp-example-client]/[tapable]/lib/Tapable.js:69:14
  
  - CachePlugin.js:40 Compiler.
    [tscomp-example-client]/[webpack]/lib/CachePlugin.js:40:4
  
  - Tapable.js:71 Compiler.applyPluginsAsync
    [tscomp-example-client]/[tapable]/lib/Tapable.js:71:13
  
  - Compiler.js:400 Compiler.
    [tscomp-example-client]/[webpack]/lib/Compiler.js:400:9
  
  - Compilation.js:577 Compilation.
    [tscomp-example-client]/[webpack]/lib/Compilation.js:577:13
  
  - Tapable.js:60 Compilation.applyPluginsAsync
    [tscomp-example-client]/[tapable]/lib/Tapable.js:60:69
  
  - Compilation.js:572 Compilation.
    [tscomp-example-client]/[webpack]/lib/Compilation.js:572:10
  
  - Tapable.js:60 Compilation.applyPluginsAsync
    [tscomp-example-client]/[tapable]/lib/Tapable.js:60:69
  
  - Compilation.js:567 Compilation.
    [tscomp-example-client]/[webpack]/lib/Compilation.js:567:9
  
  - Tapable.js:60 Compilation.applyPluginsAsync
    [tscomp-example-client]/[tapable]/lib/Tapable.js:60:69
  
  - Compilation.js:563 Compilation.
    [tscomp-example-client]/[webpack]/lib/Compilation.js:563:8
  
  - Tapable.js:60 Compilation.applyPluginsAsync
    [tscomp-example-client]/[tapable]/lib/Tapable.js:60:69
  
  - From previous event:
  
  - index.js:55 Compiler.
    [tscomp-example-client]/[html-webpack-plugin]/index.js:55:8
  
  - Tapable.js:107 Compiler.applyPluginsParallel
    [tscomp-example-client]/[tapable]/lib/Tapable.js:107:14
  
  - Compiler.js:394 Compiler.compile
    [tscomp-example-client]/[webpack]/lib/Compiler.js:394:7
  
  - Compiler.js:46 Watching.
    [tscomp-example-client]/[webpack]/lib/Compiler.js:46:17
  
  - Tapable.js:67 Compiler.next
    [tscomp-example-client]/[tapable]/lib/Tapable.js:67:11
  
  - index.js:378 Compiler.
    [tscomp-example-client]/[ts-loader]/index.js:378:9
  
  - Tapable.js:69 Compiler.next
    [tscomp-example-client]/[tapable]/lib/Tapable.js:69:14
  
  - middleware.js:119 Compiler.invalidAsyncPlugin
    [tscomp-example-client]/[webpack-dev-middleware]/middleware.js:119:3  
  - Tapable.js:71 Compiler.applyPluginsAsync
    [tscomp-example-client]/[tapable]/lib/Tapable.js:71:13
  
  - Compiler.js:44 Watching._go
    [tscomp-example-client]/[webpack]/lib/Compiler.js:44:16
  
  - Compiler.js:108 Watching.invalidate
    [tscomp-example-client]/[webpack]/lib/Compiler.js:108:8
  
  - Compiler.js:93 Watching.
    [tscomp-example-client]/[webpack]/lib/Compiler.js:93:8
  
  - NodeWatchFileSystem.js:43 NodeWatchFileSystem.
    [tscomp-example-client]/[webpack]/lib/node/NodeWatchFileSystem.js:43    :3
  
  - watchpack.js:121 EventEmitter._onTimeout
    [tscomp-example-client]/[watchpack]/lib/watchpack.js:121:7
  ```

Am I including the css in a wrong way or is this an actual bug? Inline css is not working either when I use JSX, it just disappears. 

I also try to use images by [referencing directly to them](https://github.com/beanloop/tscomp/blob/master/scripts/start.js#L266) in JSX but then the image ends up at `http://localhost:3000/static/media/beanloop.2bf0f2d5.png` but the img-tag is not updated. Is this also skit bakom tangenterna or a bug?

**Comment by Pajn** [comment]
We are using [CSS modules](https://github.com/css-modules/css-modules) as well as modules for assets so something like
```
import logo from '../assets/logo.svg'

export const Logo = () => <img src={logo} />
```

The reason for the crash is that the css modules tries to add the css file to the DOM, but when you add a link tag like that, the text should be included instead. I don't currently know how to override the css-loader just for <link>, but if you want to use global css you can write all your css inside `:global` like this:
```
:global {
  .normalCssHere {
    color: black;
  }
}
```
and require it in your top level css like this `import '../path/to.css'`

**Comment by OskarKlintrot** [comment]
Thanks, I will try it out! Would you be interested in a PR with the examples when I get it to work? I will do one example for the server as well.

**Comment by Pajn** [comment]
Yes absolutely, examples are great!

**Comment by OskarKlintrot** [comment]
Great, then I hope you will get a PR for the client before the end of this week!

`import '../path/to.css'` worked like a charm, though I emitted `:global` because VS Code didn't like that. I guess there is some settings to fix.

However, inline CSS still dosen't work, is it only CSS modules that is working or should this be working:

```
const style = {
  backgroundImage: "https://unsplash.it/1024/683/?random",
}

export default () => {
  return (
    <div>
      <img src={logo} />
    </div>
  )
}
```

I also couldn't get the image to work when I used `import logo from './logo.png'`. That just gives me a `error TS2307: Cannot find module './logo.png'.`.

**Comment by Pajn** [comment]
Inline styles should work, that's just react and has nothing to do with the webpack config.

In your example you haven't passed style to any element, is that just here or have you missed `style={style}` anywhere? 
Also I think the background image must be in the format `'url("https://unsplash.it/1024/683/?random")'`

You need typings for assets for TS to not freak out. Optimally tscomp should include them but I haven't manage to figure that out yet so add something like assets.d.ts to your project with neccesary extensions declared like:
```
declare module '*.png'
declare module '*.svg'
declare module '*.jpg'
declare module '*.gif'
```

**Comment by OskarKlintrot** [comment]
I had removed the html with the style tag instead of the image. But you are correct that the css was wrong, when I changed it to your example it started to work!

Thanks for the typings, now VS Code is not complaining anymore. However, I actually still get the same error: `(2,18): error TS2307: Cannot find module './logo.png'.`.

**Comment by OskarKlintrot** [comment]
I just tried this code in `create-react-app` (which I assume `tscomp` is built on after reading the comments in the source code) and it is working, but it is not working in `tscomp`:

```
import React from 'react';
import logo from './logo.png';
import './App.css';

export default () => {
  return (
    <img src={logo} />
  )
}
```

**Comment by OskarKlintrot** [comment]
@Pajn helper me outside of Github, the problem was that I had the target set to `es5` but it had to be `es2015`. Now `tscomp` is working like a charm for me! I will write tests to my example before I do a PR.
